### ISSUE TITLE
[Bug Report] Returning to main menu and loading into a game removes shotgun and ammo from store

### ISSUE THREAD

**Issue by ANYX-The-Artist** [hades/firearmlicense#1]
Basically, everything in the title.
Upon first game load, the shotgun and ammo are listed and terminal knows the keywords, as expected.
If you were to save/quit and reload, or return to the main menu by any other means, and then reload a save file OR start a new save, shotgun and ammo will no longer be found in the store menu, and the terminal no longer knows the keywords.

**Comment by hades** [comment]
Thanks for the report, I'll take a look as soon as I can :)
